host coverage badge on Github pages
Updating the coverage.svg required commits to be signed hence rejecting the push.
Host the coverage.svg on Github pages where verified commits is not a requirement

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -59,33 +59,21 @@ jobs:
           git checkout -
 
       - name: Generate coverage badge
-        if: github.ref == 'refs/heads/main'
+        # if: github.ref == 'refs/heads/main'
         run: |
-          rm -f coverage.svg
-          coverage-badge -o coverage.svg
+          mkdir -p public
+          coverage-badge -o public/coverage.svg
 
-      - name: Check if coverage.svg changed
-        if: github.ref == 'refs/heads/main'
-        id: verify-changed-files
+      - name: Check coverage.svg
         run: |
-          git fetch origin main
-          if git diff --quiet origin/main -- coverage.svg; then
-            echo "files_changed=false" >> $GITHUB_OUTPUT
-          else
-            echo "files_changed=true" >> $GITHUB_OUTPUT
-          fi
+          ls -l public
+          cat public/coverage.svg || echo "coverage.svg not found"
 
-      - name: Commit updated coverage badge
-        if: steps.verify-changed-files.outputs.files_changed == 'true'
-        run: |
-          git config --local user.name "github-actions[bot]"
-          git config --local user.email "github-actions[bot]@users.noreply.github.com"
-          git add coverage.svg
-          git commit -m "update coverage badge [skip ci]"
-
-      - name: Push changes
-        if: steps.verify-changed-files.outputs.files_changed == 'true'
-        uses: ad-m/github-push-action@master
+      - name: Deploy coverage badge to GitHub Pages
+        # if: github.ref == 'refs/heads/main'
+        uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          branch: main
+          publish_dir: ./public
+          publish_branch: gh-pages
+          destination_dir: coverage
